"""
Django settings for barhop project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'g=vsfr=5)h9nc4*sco!j#qe=@_=^u49f9%*z*56h#x0y7#-=15'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', 'barhop.io', 'www.barhop.io']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ws4redis',
    't_auth',
    'djrill',
    'payment',
    'trophy',
    'route',
    'block',
    'managed_account',

)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'barhop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.static',
                'ws4redis.context_processors.default'
            ],
        },
    },
]

WSGI_APPLICATION = 'ws4redis.django_runserver.application'

SESSION_ENGINE = 'redis_sessions.session'

SESSION_REDIS_PREFIX = 'session'

WS4REDIS_HEARTBEAT = '--heartbeat--'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_USER_MODEL = 't_auth.CustomUser'

AUTHENTICATION_BACKENDS = (
    't_auth.backends.EmailAuthBackend',
)

WEBSOCKET_URL = '/ws/'

WS4REDIS_EXPIRE = 3600

WS4REDIS_PREFIX = 'barhop'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Belize'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

INCLUDE_REGISTER_URL = True
INCLUDE_AUTH_URLS = True

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


# EMAIL_BACKEND = "djrill.mail.backends.djrill.DjrillBackend"
# MANDRILL_API_KEY = "FvnSc13k9P1L6lB6wYxpsA"
# DEFAULT_FROM_EMAIL = 'no-reply@barhop.com'
# LOGIN_REDIRECT_URL = '/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587

EMAIL_HOST_USER = 'developer.realtordaddy@gmail.com'
EMAIL_HOST_PASSWORD = 'dfvyubjkcjppdtvd'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'no-reply@barhop.com'



#################### development #########################
TWILIO_ACCOUNT_SID = 'ACcffb21a7aa455f328e522856741b8fe8'
TWILIO_AUTH_TOKEN = '482858ebebffcf4c951c03960d428768'
BARHOP_NUMBER = '+17605136261'


########################## Stagging #####################
# TWILIO_ACCOUNT_SID = 'AC471c5467918a8a7d7a96460312c4eb44'
# TWILIO_AUTH_TOKEN = '5bc6f4e25d91e42b8785b022ec1217cd'
# BARHOP_NUMBER = '+12145714438'


# Live
# ACCOUNT_SID = 'SK24c9ab44f74d5e3095578fc73dcbd8bb'
# AUTH_TOKEN = 'HXEElKpz9dpj27I8WqUbQHMwsYDEOXZ6'

# STRIPE

############ DEV #################################### 
# STRIPE_SECRET_KEY = 'sk_test_grh6SBR6cCz3ewKGAJqLA6iN'
# STRIPE_PUBLIC_KEY = 'pk_test_DeV2O9iccNljVHoJNu7IrHs8'

############### Test ################################
STRIPE_SECRET_KEY = 'sk_test_FkiPFFIuSj3OQdoXkcQJLDyg'
STRIPE_PUBLIC_KEY = 'pk_test_3dUAb8qI7WYyvZSkH0ewibc8'

############### Live ##################################
# STRIPE_SECRET_KEY = 'sk_live_CHevdKfuLlI7oBnD1EOZSWD7'
# STRIPE_PUBLIC_KEY = 'pk_live_vPahI3p8aXltdaC31013tFqt'


SALES_TAX_PERCENT = 8.25  #8.25%
BARHOP_TIP = 18    #18%

# BITLY
BITLY_ACCESS_TOKEN = '31d7102dad05bf73b9dfd1bdffdfefc65a17b6df'


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s %(module)s] %(levelname)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

